name: learn-github-actions # 任意のワークフロー名を記述する

on: # 実行のトリガーを設定する
  pull_request: # プルリクエストの作成をトリガーとする
    branches:
      - main # プルリクエストの対象ブランチをmainに限定する

jobs:
  run-unit-tests: # 任意のジョブ名を記述する
    runs-on: ubuntu-latest # Linuxの実行環境を指定する

    # ジョブのステップを記述する
    steps:
      # リポジトリのコードをチェックアウト
      - uses: actions/checkout@v4

      # Goのインストール
      - name: Setup Go 1.22.4
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"

      # 単体テストの実行
      - name: Run unit tests
        run: go test -v ./...
